FROM python:3.7-slim as base

FROM base as builder

RUN mkdir /install
WORKDIR /install
COPY requirements.txt /requirements.txt
RUN pip install --install-option="--prefix=/install" -r /requirements.txt


FROM base
WORKDIR /app

ADD main.py /app
ADD generate_key.py /app

ENV PYTHONUNBUFFERED=true
CMD [ "python3", "main.py" ]